// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzvowOWoK-h0TWtbmLXCpFjWa2FS1RPSs',
    appId: '1:58175339864:web:7994728427aa7e4bd5392d',
    messagingSenderId: '58175339864',
    projectId: 'doan-b77c1',
    authDomain: 'doan-b77c1.firebaseapp.com',
    storageBucket: 'doan-b77c1.appspot.com',
    measurementId: 'G-REJJBZP089',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAflRfrE7fTXsKAMn2d1lpxuQbBGe1dwro',
    appId: '1:58175339864:android:8902c7f757206a2ad5392d',
    messagingSenderId: '58175339864',
    projectId: 'doan-b77c1',
    storageBucket: 'doan-b77c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtzSu0G9j3HUifoyD81DVXHiV36bQBkKQ',
    appId: '1:58175339864:ios:4c03303dfffa92cdd5392d',
    messagingSenderId: '58175339864',
    projectId: 'doan-b77c1',
    storageBucket: 'doan-b77c1.appspot.com',
    androidClientId: '58175339864-brp2235cnluoevu4f35sai85jvl38lm6.apps.googleusercontent.com',
    iosClientId: '58175339864-jjh22hvqdtcag4f619qbud3b5bi437kk.apps.googleusercontent.com',
    iosBundleId: 'com.example.doan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtzSu0G9j3HUifoyD81DVXHiV36bQBkKQ',
    appId: '1:58175339864:ios:754780e86aa1da55d5392d',
    messagingSenderId: '58175339864',
    projectId: 'doan-b77c1',
    storageBucket: 'doan-b77c1.appspot.com',
    androidClientId: '58175339864-brp2235cnluoevu4f35sai85jvl38lm6.apps.googleusercontent.com',
    iosClientId: '58175339864-ftas23qs9bv0i5t4d1fa7f3igln38j25.apps.googleusercontent.com',
    iosBundleId: 'com.example.doan.RunnerTests',
  );
}
